name: PlannerBuild

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y.%m.%d/%H.%M')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build APK debug project
        run: gradle assembleDebug

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
          name: Planner - ${{ env.date_today }}
          tag_name: d/${{ env.date_today }}